###
GET http://localhost:3000/post
###
GET http://localhost:3000/post?sender=12345

###
GET http://localhost:3000/post/63766da7862694717ecaf37d

###

POST http://localhost:3000/post
Content-Type: application/json

{
    "message":"this is my new message 2",
    "sender": "12345"
}
###

###
PUT http://localhost:3000/post/637924f9e9d851d7fdf595b
Content-Type: application/json

{
    "message":"change message",
    "sender":"12345"
}
###
