###
GET http://localhost:3000/post
//Authorization:jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzODI2ZjMyZTU0NTEyYjVkNjgyYTQ5ZiIsImlhdCI6MTY2OTQ5MjUzNCwiZXhwIjoxNjY5NDk2MTM0fQ.gCtV1S5jekI_Mo5bm0I_h0Z1ZQ0myB_yuAQsMtsUcSE

###
GET http://localhost:3000/post?sender=12345

###
GET http://localhost:3000/post/63766da7862694717ecaf37d

###

POST http://localhost:3000/post
Authorization:jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzODI2ZjMyZTU0NTEyYjVkNjgyYTQ5ZiIsImlhdCI6MTY2OTQ5MjUzNCwiZXhwIjoxNjY5NDk2MTM0fQ.gCtV1S5jekI_Mo5bm0I_h0Z1ZQ0myB_yuAQsMtsUcSE
Content-Type: application/json

{
    "message":"this is my new message 2",
    "sender": "12345"
}
###

###
PUT http://localhost:3000/post/637924f9e9d851d7fdf595b
Content-Type: application/json

{
    "message":"change message",
    "sender":"12345"
}
###

###
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "password": "12345"
}

###

###
POST  http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "password": "12345"
}

###